# Brother TD-2020 label printer driver, repackaged from Brother's official
# i386 LPR + CUPS-wrapper RPMs. The filter chain CUPS ends up running is:
#
#   brother_lpdwrapper_td2020 (sh)  -> brcupsconfpt1 (i386 ELF, reads options)
#     -> filtertd2020 (sh) -> psconvertpt1 (sh, calls `gs`) -> rastertobrpt1 (i386 ELF)
#
# Two things make this awkward on NixOS and are handled here / by the module:
#   * The i386 binaries build their data paths internally with
#     sprintf("/opt/brother/PTouch/%s/..."), so the driver tree must exist at
#     that literal path at runtime. modules/print-server.nix symlinks
#     /opt/brother -> this package via systemd.tmpfiles.
#   * The PPD and the wrapper filter are generated by the installer's own
#     here-docs. We re-run exactly those here-docs at build time so the output
#     is byte-for-byte what Brother ships, just pointed at $out.
{
  lib,
  stdenv,
  fetchurl,
  libarchive,
  patchelf,
  glibc_i686,
  coreutils,
  gnused,
  gnugrep,
  gawk,
  file,
  which,
  ghostscript,
  poppler-utils,
  psutils,
  cups,
}:

stdenv.mkDerivation {
  pname = "brother-td2020";
  version = "1.0.1-0";

  srcs = [
    (fetchurl {
      url = "https://download.brother.com/welcome/dlfp002209/td2020lpr-1.0.1-0.i386.rpm";
      hash = "sha256-BhL3ZCMEu0zdKk6NMverz+klnoM+JPykyxN0AE9NFCw=";
    })
    (fetchurl {
      url = "https://download.brother.com/welcome/dlfp002211/td2020cupswrapper-1.0.1-0.i386.rpm";
      hash = "sha256-Gb/Mqe7AVxLGjU0gEsmX50eFHYW8D+mlxRtyJKrc9Kc=";
    })
  ];

  nativeBuildInputs = [
    libarchive
    patchelf
  ];

  dontConfigure = true;
  dontBuild = true;

  unpackPhase = ''
    runHook preUnpack
    mkdir -p src
    for f in $srcs; do
      bsdtar -xf "$f" -C src
    done
    runHook postUnpack
  '';

  installPhase = ''
    runHook preInstall

    # 1. Driver tree at the literal path the binaries expect (see header note).
    mkdir -p $out/opt/brother/PTouch
    cp -r src/opt/brother/PTouch/td2020 $out/opt/brother/PTouch/

    # 2. Regenerate the PPD and the CUPS wrapper filter by re-running the
    #    installer's own here-docs with our output paths.
    mkdir -p $out/share/cups/model $out/lib/cups/filter
    cw=$out/opt/brother/PTouch/td2020/cupswrapper/cupswrappertd2020pt1

    ppd_file_name=$out/share/cups/model/brother_td2020_printer_en.ppd \
    ppd_file_name1=/dev/null \
      sh -c "$(awk '/cat <<ENDOFPPDFILE/{f=1} f{print} /^ENDOFPPDFILE/{if(f)exit}' "$cw")"

    brotherlpdwrapper=$out/lib/cups/filter/brother_lpdwrapper_td2020 \
      sh -c "$(awk '/cat <<!ENDOFWFILTER!/{f=1} f{print} /^!ENDOFWFILTER!/{if(f)exit}' "$cw")"
    chmod +x $out/lib/cups/filter/brother_lpdwrapper_td2020

    # 3. The shell filters shell out to gs, file, mktemp, pstops, ... which are
    #    not on cupsd's PATH. Pin a known-good PATH right after the shebang; the
    #    child filters (filtertd2020, psconvertpt1) inherit it.
    sed -i '1a export PATH=${
      lib.makeBinPath [
        coreutils
        gnused
        gnugrep
        gawk
        file
        which
        ghostscript
        poppler-utils
        psutils
        cups
      ]
    }''${PATH:+:$PATH}' \
      $out/lib/cups/filter/brother_lpdwrapper_td2020

    # 4. Point the i386 ELF filters at the 32-bit loader/glibc. autoPatchelfHook
    #    refuses foreign-arch binaries, so do it by hand; they need only
    #    libc/libm, both in glibc_i686.
    for rel in lpd/rastertobrpt1 lpd/brpapertoolcups cupswrapper/brcupsconfpt1; do
      patchelf \
        --set-interpreter ${glibc_i686}/lib/ld-linux.so.2 \
        --set-rpath ${glibc_i686}/lib \
        $out/opt/brother/PTouch/td2020/$rel
    done

    runHook postInstall
  '';

  meta = {
    description = "Brother TD-2020 label printer CUPS/LPR driver (proprietary)";
    homepage = "https://support.brother.com/g/b/downloadtop.aspx?c=us&lang=en&prod=lptd2020eus";
    license = lib.licenses.unfree;
    sourceProvenance = with lib.sourceTypes; [ binaryNativeCode ];
    platforms = [ "x86_64-linux" ];
  };
}
