- id: '0000000000000'
  alias: Sunrise
  description: ''
  triggers:
  - trigger: sun
    event: sunrise
    offset: 0
  conditions: []
  actions:
  - type: turn_on
    device_id: REPLACE_WITH_YOUR_DEVICE_ID
    entity_id: REPLACE_WITH_YOUR_LIGHT_ENTITY_ID
    domain: light
    brightness_pct: 30
  - delay:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  - type: turn_on
    device_id: REPLACE_WITH_YOUR_DEVICE_ID
    entity_id: REPLACE_WITH_YOUR_LIGHT_ENTITY_ID
    domain: light
    brightness_pct: 100
  mode: single
